### ISSUE TITLE
含まれていないファイル

### ISSUE THREAD

**Issue by tohka** [amx-project/kuwanauchi#2]
`kuwanauchi_datalist.csv` をリストを正とした際（ G 空間情報センターの方はすべて見れていません）、各リポジトリに展開されていないファイルがありました。

- `01405-4304.zip`
- `01424-4315.zip`
- `02307-4200.zip`
- `02343-4202.zip`
- `02384-4201.zip`
- `02387-4201.zip`
- `02401-4234.zip`
- `02425-4211.zip`
- `02443-4204.zip`
- `07211-3802.zip`
- `07444-3804.zip`
- `07521-3802.zip`
- `07522-3802.zip`
- `07547-3842.zip`
- `15202-1104.zip`
- `15210-1131.zip`
- `15222-1107.zip`
- `15224-1109.zip`
- `15225-1106.zip`
- `15385-1113.zip`
- `15482-1131.zip`
- `30403-1702.zip`
- `31381-2702.zip`
- `32301-2800.zip`
- `32383-2802.zip`
- `32385-2802.zip`
- `32503-2804.zip`
- `33322-2600.zip`
- `33323-2600.zip`
- `33645-2605.zip`
- `33646-2605.zip`
- `34402-2420.zip`
- `35421-2505.zip`
- `36422-4800.zip`
- `36466-4802.zip`
- `37381-4700.zip`
- `38209-5022.zip`
- `38302-5022.zip`
- `38385-5001.zip`
- `38404-5000.zip`
- `40402-2903.zip`
- `40444-2912.zip`
- `40463-2911.zip`
- `40483-2904.zip`
- `40641-2909.zip`
- `41324-3011.zip`
- `41364-3000.zip`
- `41443-3001.zip`
- `42206-3106.zip`
- `42342-3117.zip`
- `42382-3104.zip`
- `42421-3105.zip`
- `43322-3315.zip`
- `43361-3302.zip`
- `43365-3302.zip`
- `43385-3304.zip`
- `43422-3305.zip`
- `43427-3300.zip`
- `43430-3305.zip`
- `43463-3306.zip`
- `44321-3201.zip`
- `44501-3205.zip`
- `44522-3231.zip`
- `45301-3500.zip`
- `45345-3502.zip`
- `46207-3405.zip`
- `46211-3422.zip`
- `46302-3400.zip`
- `46344-3402.zip`
- `46383-3403.zip`
- `46467-3442.zip`
- `46485-3404.zip`

**Comment by mapconcierge** [comment]
ダブルチェックありがとうございます！！！ こちら確認します！

**Comment by mapconcierge** [comment]
# 作業確認用チェックリスト
- [x] `01405-4304.zip` https://github.com/amx-project/kuwanauchi01hokkaido/commit/2b131764823061872cb5e9659950bdcfe4c46774
- [x] `01424-4315.zip` https://github.com/amx-project/kuwanauchi01hokkaido/commit/2b131764823061872cb5e9659950bdcfe4c46774
- [x] `02307-4200.zip` https://github.com/amx-project/kuwanauchi02aomori/commit/b30878b5c3a426498377880cd3c7b8186c29d67e
- [x] `02343-4202.zip` https://github.com/amx-project/kuwanauchi02aomori/commit/b30878b5c3a426498377880cd3c7b8186c29d67e
- [x] `02384-4201.zip` https://github.com/amx-project/kuwanauchi02aomori/commit/b30878b5c3a426498377880cd3c7b8186c29d67e
- [x] `02387-4201.zip` https://github.com/amx-project/kuwanauchi02aomori/commit/b30878b5c3a426498377880cd3c7b8186c29d67e
- [x] `02401-4234.zip` https://github.com/amx-project/kuwanauchi02aomori/commit/b30878b5c3a426498377880cd3c7b8186c29d67e
- [x] `02425-4211.zip` https://github.com/amx-project/kuwanauchi02aomori/commit/b30878b5c3a426498377880cd3c7b8186c29d67e
- [x] `02443-4204.zip` https://github.com/amx-project/kuwanauchi02aomori/commit/b30878b5c3a426498377880cd3c7b8186c29d67e
- [x] `07211-3802.zip` https://github.com/amx-project/kuwanauchi07fukushima/commit/b79c961e21b2e5cf975beef9e1a45e4a664e941a
- [x] `07444-3804.zip` https://github.com/amx-project/kuwanauchi07fukushima/commit/b79c961e21b2e5cf975beef9e1a45e4a664e941a
- [x] `07521-3802.zip` https://github.com/amx-project/kuwanauchi07fukushima/commit/b79c961e21b2e5cf975beef9e1a45e4a664e941a
- [x] `07522-3802.zip` https://github.com/amx-project/kuwanauchi07fukushima/commit/b79c961e21b2e5cf975beef9e1a45e4a664e941a
- [x] `07547-3842.zip` https://github.com/amx-project/kuwanauchi07fukushima/commit/b79c961e21b2e5cf975beef9e1a45e4a664e941a
- [x] `15202-1104.zip` https://github.com/amx-project/kuwanauchi15niigata/commit/ce3fb53480871b6defbe3371b4a4eff924080d4a https://github.com/amx-project/kuwanauchi15niigata/commit/deb7a75097f52d416eeb40bfd833480ab34d2092
- [x] `15210-1131.zip` https://github.com/amx-project/kuwanauchi15niigata/commit/ce3fb53480871b6defbe3371b4a4eff924080d4a
- [x] `15222-1107.zip` https://github.com/amx-project/kuwanauchi15niigata/commit/ce3fb53480871b6defbe3371b4a4eff924080d4a
- [x] `15224-1109.zip` https://github.com/amx-project/kuwanauchi15niigata/commit/ce3fb53480871b6defbe3371b4a4eff924080d4a
- [x] `15225-1106.zip` https://github.com/amx-project/kuwanauchi15niigata/commit/ce3fb53480871b6defbe3371b4a4eff924080d4a
- [x] `15385-1113.zip` https://github.com/amx-project/kuwanauchi15niigata/commit/ce3fb53480871b6defbe3371b4a4eff924080d4a
- [x] `15482-1131.zip` https://github.com/amx-project/kuwanauchi15niigata/commit/ce3fb53480871b6defbe3371b4a4eff924080d4a
- [x] `30403-1702.zip` https://github.com/amx-project/kuwanauchi30wakayama/commit/502082ab9b946dda7bb5bb17cf659dd72283abde
- [x] `31381-2702.zip` https://github.com/amx-project/kuwanauchi31tottori/commit/056cf75c035640204fea963040427dda961ff54c
- [x] `32301-2800.zip` https://github.com/amx-project/kuwanauchi32shimane/commit/9b62ee96ea8bb5561aa1c4501c1421c5b6ad1b7b
- [x] `32383-2802.zip` https://github.com/amx-project/kuwanauchi32shimane/commit/9b62ee96ea8bb5561aa1c4501c1421c5b6ad1b7b
- [x] `32385-2802.zip` https://github.com/amx-project/kuwanauchi32shimane/commit/9b62ee96ea8bb5561aa1c4501c1421c5b6ad1b7b
- [x] `32503-2804.zip` https://github.com/amx-project/kuwanauchi32shimane/commit/9b62ee96ea8bb5561aa1c4501c1421c5b6ad1b7b
- [x] `33322-2600.zip` https://github.com/amx-project/kuwanauchi33okayama/commit/837fc2f82cdee3c43d10d0505522859edefe4a19
- [x] `33323-2600.zip` https://github.com/amx-project/kuwanauchi33okayama/commit/837fc2f82cdee3c43d10d0505522859edefe4a19
- [x] `33645-2605.zip` https://github.com/amx-project/kuwanauchi33okayama/commit/837fc2f82cdee3c43d10d0505522859edefe4a19
- [x] `33646-2605.zip` https://github.com/amx-project/kuwanauchi33okayama/commit/837fc2f82cdee3c43d10d0505522859edefe4a19
- [x] `34402-2420.zip` https://github.com/amx-project/kuwanauchi34hiroshima/commit/b6a61e5c335bc07bb5236b391d14114af13d4eec
- [x] `35421-2505.zip` https://github.com/amx-project/kuwanauchi35yamaguchi/commit/c602393ea8a0bc83a1ebd3b71d79ff1bf8134605
- [x] `36422-4800.zip` https://github.com/amx-project/kuwanauchi36tokushima/commit/a16ea7db7f43627b332ca2040b1fe00f7b4ec486
- [x] `36466-4802.zip` https://github.com/amx-project/kuwanauchi36tokushima/commit/a16ea7db7f43627b332ca2040b1fe00f7b4ec486
- [x] `37381-4700.zip` https://github.com/amx-project/kuwanauchi37kagawa/commit/04bc48e9020aec9939372feec4994c42d496b858
- [x] `38209-5022.zip` https://github.com/amx-project/kuwanauchi38ehime/commit/4134f20d69b265279e095256e5a2514fd7b56076
- [x] `38302-5022.zip` https://github.com/amx-project/kuwanauchi38ehime/commit/4134f20d69b265279e095256e5a2514fd7b56076
- [x] `38385-5001.zip` https://github.com/amx-project/kuwanauchi38ehime/commit/4134f20d69b265279e095256e5a2514fd7b56076
- [x] `38404-5000.zip` https://github.com/amx-project/kuwanauchi38ehime/commit/4134f20d69b265279e095256e5a2514fd7b56076
- [x] `40402-2903.zip` https://github.com/amx-project/kuwanauchi40fukuoka/commit/67bb93e8520aaeaf343c0c09f991de55db015fa4
- [x] `40444-2912.zip` https://github.com/amx-project/kuwanauchi40fukuoka/commit/67bb93e8520aaeaf343c0c09f991de55db015fa4
- [x] `40463-2911.zip` https://github.com/amx-project/kuwanauchi40fukuoka/commit/67bb93e8520aaeaf343c0c09f991de55db015fa4
- [x] `40483-2904.zip` https://github.com/amx-project/kuwanauchi40fukuoka/commit/67bb93e8520aaeaf343c0c09f991de55db015fa4
- [x] `40641-2909.zip` https://github.com/amx-project/kuwanauchi40fukuoka/commit/67bb93e8520aaeaf343c0c09f991de55db015fa4
- [x] `41324-3011.zip` https://github.com/amx-project/kuwanauchi41saga/commit/187947a5f1edf09f3c5c3fd5f38a2758e880ff8f
- [x] `41364-3000.zip` https://github.com/amx-project/kuwanauchi41saga/commit/187947a5f1edf09f3c5c3fd5f38a2758e880ff8f
- [x] `41443-3001.zip` https://github.com/amx-project/kuwanauchi41saga/commit/187947a5f1edf09f3c5c3fd5f38a2758e880ff8f
- [x] `42206-3106.zip` https://github.com/amx-project/kuwanauchi42nagasaki/commit/9cd2059785bb4ff4a953365cfb0288a335415214
- [x] `42342-3117.zip` https://github.com/amx-project/kuwanauchi42nagasaki/commit/9cd2059785bb4ff4a953365cfb0288a335415214
- [x] `42382-3104.zip` https://github.com/amx-project/kuwanauchi42nagasaki/commit/9cd2059785bb4ff4a953365cfb0288a335415214
- [x] `42421-3105.zip` https://github.com/amx-project/kuwanauchi42nagasaki/commit/9cd2059785bb4ff4a953365cfb0288a335415214
- [x] `43322-3315.zip` https://github.com/amx-project/kuwanauchi43kumamoto/commit/3857bd825c1c83df7e2f816b524ac4e95b87085f
- [x] `43361-3302.zip` https://github.com/amx-project/kuwanauchi43kumamoto/commit/3857bd825c1c83df7e2f816b524ac4e95b87085f
- [x] `43365-3302.zip` https://github.com/amx-project/kuwanauchi43kumamoto/commit/3857bd825c1c83df7e2f816b524ac4e95b87085f
- [x] `43385-3304.zip` https://github.com/amx-project/kuwanauchi43kumamoto/commit/3857bd825c1c83df7e2f816b524ac4e95b87085f
- [x] `43422-3305.zip` https://github.com/amx-project/kuwanauchi43kumamoto/commit/3857bd825c1c83df7e2f816b524ac4e95b87085f
- [x] `43427-3300.zip` https://github.com/amx-project/kuwanauchi43kumamoto/commit/3857bd825c1c83df7e2f816b524ac4e95b87085f
- [x] `43430-3305.zip` https://github.com/amx-project/kuwanauchi43kumamoto/commit/3857bd825c1c83df7e2f816b524ac4e95b87085f
- [x] `43463-3306.zip` https://github.com/amx-project/kuwanauchi43kumamoto/commit/3857bd825c1c83df7e2f816b524ac4e95b87085f
- [x] `44321-3201.zip` https://github.com/amx-project/kuwanauchi44oita/commit/d0bf7d8fb22dd7197ee3af09090c701c11bea1ba
- [x] `44501-3205.zip` https://github.com/amx-project/kuwanauchi44oita/commit/d0bf7d8fb22dd7197ee3af09090c701c11bea1ba
- [x] `44522-3231.zip` https://github.com/amx-project/kuwanauchi44oita/commit/d0bf7d8fb22dd7197ee3af09090c701c11bea1ba
- [x] `45301-3500.zip` https://github.com/amx-project/kuwanauchi45miyazaki/commit/ba6c9af2af9e9561a2334674118cc7151ab7bc1f
- [x] `45345-3502.zip` https://github.com/amx-project/kuwanauchi45miyazaki/commit/ba6c9af2af9e9561a2334674118cc7151ab7bc1f
- [x] `46207-3405.zip` https://github.com/amx-project/kuwanauchi46kagoshima/commit/528832f5458afcab038df60ef2e9abb364890c94
- [x] `46211-3422.zip` https://github.com/amx-project/kuwanauchi46kagoshima/commit/528832f5458afcab038df60ef2e9abb364890c94
- [x] `46302-3400.zip` https://github.com/amx-project/kuwanauchi46kagoshima/commit/528832f5458afcab038df60ef2e9abb364890c94
- [x] `46344-3402.zip` https://github.com/amx-project/kuwanauchi46kagoshima/commit/528832f5458afcab038df60ef2e9abb364890c94
- [x] `46383-3403.zip` https://github.com/amx-project/kuwanauchi46kagoshima/commit/528832f5458afcab038df60ef2e9abb364890c94
- [x] `46467-3442.zip` https://github.com/amx-project/kuwanauchi46kagoshima/commit/528832f5458afcab038df60ef2e9abb364890c94
- [x] `46485-3404.zip` https://github.com/amx-project/kuwanauchi46kagoshima/commit/528832f5458afcab038df60ef2e9abb364890c94

**Comment by mapconcierge** [comment]
北海道のデータ確かに欠けていました。追加アップロード完了です。
https://github.com/amx-project/kuwanauchi01hokkaido/commit/2b131764823061872cb5e9659950bdcfe4c46774

**Comment by mapconcierge** [comment]
青森県修正完了！！
https://github.com/amx-project/kuwanauchi02aomori/commit/b30878b5c3a426498377880cd3c7b8186c29d67e

**Comment by mapconcierge** [comment]
福島県修正完了！！
 https://github.com/amx-project/kuwanauchi07fukushima/commit/b79c961e21b2e5cf975beef9e1a45e4a664e941a

**Comment by mapconcierge** [comment]
新潟県修正完了！！
 https://github.com/amx-project/kuwanauchi15niigata/commit/ce3fb53480871b6defbe3371b4a4eff924080d4a

**Comment by mapconcierge** [comment]
和歌山県修正完了！
https://github.com/amx-project/kuwanauchi30wakayama/commit/502082ab9b946dda7bb5bb17cf659dd72283abde

**Comment by mapconcierge** [comment]
鳥取県修正完了！
https://github.com/amx-project/kuwanauchi31tottori/commit/056cf75c035640204fea963040427dda961ff54c

**Comment by mapconcierge** [comment]
島根県修正完了
 https://github.com/amx-project/kuwanauchi32shimane/commit/9b62ee96ea8bb5561aa1c4501c1421c5b6ad1b7b

**Comment by mapconcierge** [comment]
岡山県修正完了！
 https://github.com/amx-project/kuwanauchi33okayama/commit/837fc2f82cdee3c43d10d0505522859edefe4a19

**Comment by mapconcierge** [comment]
広島県修正完了！！
https://github.com/amx-project/kuwanauchi34hiroshima/commit/b6a61e5c335bc07bb5236b391d14114af13d4eec

**Comment by mapconcierge** [comment]
山口県修正完了！！
https://github.com/amx-project/kuwanauchi35yamaguchi/commit/c602393ea8a0bc83a1ebd3b71d79ff1bf8134605

**Comment by mapconcierge** [comment]
徳島県修正完了！！
https://github.com/amx-project/kuwanauchi36tokushima/commit/a16ea7db7f43627b332ca2040b1fe00f7b4ec486

**Comment by mapconcierge** [comment]
香川県修正完了！！
https://github.com/amx-project/kuwanauchi37kagawa/commit/04bc48e9020aec9939372feec4994c42d496b858

**Comment by mapconcierge** [comment]
愛媛県修正完了！！
 https://github.com/amx-project/kuwanauchi38ehime/commit/4134f20d69b265279e095256e5a2514fd7b56076

**Comment by mapconcierge** [comment]
福岡県修正完了！
 https://github.com/amx-project/kuwanauchi40fukuoka/commit/67bb93e8520aaeaf343c0c09f991de55db015fa4

**Comment by mapconcierge** [comment]
佐賀県修正完了！
 https://github.com/amx-project/kuwanauchi41saga/commit/187947a5f1edf09f3c5c3fd5f38a2758e880ff8f

**Comment by mapconcierge** [comment]
長崎県修正完了！
 https://github.com/amx-project/kuwanauchi42nagasaki/commit/9cd2059785bb4ff4a953365cfb0288a335415214

**Comment by mapconcierge** [comment]
大分県修正完了！
 https://github.com/amx-project/kuwanauchi44oita/commit/d0bf7d8fb22dd7197ee3af09090c701c11bea1ba

**Comment by mapconcierge** [comment]
宮崎県修正完了！！！
 https://github.com/amx-project/kuwanauchi45miyazaki/commit/ba6c9af2af9e9561a2334674118cc7151ab7bc1f

**Comment by mapconcierge** [comment]
熊本県修正完了！！
 https://github.com/amx-project/kuwanauchi43kumamoto/commit/3857bd825c1c83df7e2f816b524ac4e95b87085f

**Comment by mapconcierge** [comment]
鹿児島県修正完了！！！！！
 https://github.com/amx-project/kuwanauchi46kagoshima/commit/528832f5458afcab038df60ef2e9abb364890c94

**Comment by mapconcierge** [comment]
閉じます！

**Comment by mapconcierge** [comment]
新潟県の 15202-1104 だけ欠けていたようで、再度修正。
https://github.com/amx-project/kuwanauchi15niigata/commit/deb7a75097f52d416eeb40bfd833480ab34d2092
